AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 with VPC Stack.
Parameters:
  VPCStackName:
    Type: String
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      ImageId: ami-0f36dcfcc94112ea1
      SubnetId:
        Fn::ImportValue: !Sub "${VPCStackName}-SubnetId"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${VPCStackName}-SecurityGroupId"
