AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 instance setuped by userdata.
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  AMIID:
    Type: AWS::EC2::Image::Id
    Default: ami-0f36dcfcc94112ea1
  SubnetId:
    Type: String
    Default: subnet-08f0feea861254e3e
  SecurityGroupId:
    Type: String
    Default: sg-d0c79999
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIID
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v \
          --region ${AWS::Region} \
          --stack ${AWS::StackName} \
          --resource WebServer
    Metadata:
      Comment: Install Apache
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
              # wget: []
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
              mode: "000400"
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WebServer.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v \
                  --stack  ${AWS::StackName} \
                  --resource WebServer \
                  --region ${AWS::Region}
                runas=root
          services:
            sysvinit:
              httpd:
                enabled: "true"
                ensureRunning: "true"
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
