AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 instance setuped by userdata.
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  AMIID:
    Type: AWS::EC2::Image::Id
    Default: ami-0f36dcfcc94112ea1
  SubnetId:
    Type: String
    Default: subnet-08f0feea861254e3e
  SecurityGroupId:
    Type: String
    Default: sg-d0c79999
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIID
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install ec2-net-utils -y
          service httpd start
