AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 by NestedStack.
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://PLEASE-REPLACE-YOUR-BUCKET-NAME.s3.ap-northeast-1.amazonaws.com/vpc_subnet_sg.yaml
  WebServerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://PLEASE-REPLACE-YOUR-BUCKET-NAME.s3.ap-northeast-1.amazonaws.com/ec2.yaml
      Parameters:
        SubnetId: !GetAtt VPCStack.Outputs.SubnetId
        SecurityGroupId: !GetAtt VPCStack.Outputs.SecurityGroupId
# Outputs:
#   VPCId:
#     Value: !GetAtt VPCStack.Outputs.VPCId
#     Export:
#       Name: !Sub "${AWS::StackName}-VpcId"
